version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package.json" }}
            - npm-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: npm-v1-{{ checksum "package.json" }}
      - run:
          name: Run Application
          command: npm start
      - run:
          name: Run Application
          command: npm start

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
